title: Ahmed M. Hasan
logo: /assets/img/headshot_circle.png
description: Entry-level data analyst with a strong background in statistical analysis, data visualization, and SQL. Passionate about uncovering insights from complex datasets to drive informed business decisions.
template:
  name: github-slideshow
  repo: caption-this-template
  description: 'A robot powered training repository :robot:'
#show-download: True
theme: jekyll-theme-minimal
