title: Ahmed M. Hasan
logo: /assets/img/headshot_circle.png
description: ### Profile
Entry-level data analyst with a strong background in statistical analysis, data visualization, and SQL. Passionate about uncovering insights from complex datasets to drive informed business decisions.

### Technical Skills
  - Python (Pandas, NumPy, SciPy, MatPlotLib)
  - SQL (SQL Server, MySQL, PostgreSQL)
  - Excel (VLookup, Pivot Tables)
  - Tableau (Certification In Progress)
  - Power BI (Certification PL-300 In Progress)
  - R
#show-download: True
theme: jekyll-theme-minimal
