title: Ahmed M. Hasan
logo: /assets/img/headshot_circle.png
description: Entry-level data analyst with a strong background in statistical analysis, data visualization, and SQL. Passionate about uncovering insights from complex datasets to drive informed business decisions.
preferences:
- type: radio
  name: gitTool
  label: Preferred Git tool
  description: Learn right from the web UI, or using your chosen tool
  options:
  - label: Use the GitHub.com web interface
    value: dotcom
  - label: Use the command line
    value: cli
  - label: Use Visual Studio Code
    value: vscode
#show-download: True
theme: jekyll-theme-minimal
