title: Ahmed M. Hasan
logo: /assets/img/headshot_circle.png
description: Entry-level data analyst with a strong background in statistical analysis using Python and Rstudio, data visualization using Power BI and Tableau, and database query using SQL and spreadsheet using Excel. "
 Passionate about uncovering insights from complex datasets to drive informed business decisions.
author:
  # Biographic information
  #avatar           : "profile.png"
  name             : "Your Sidebar Name"
  pronouns         : # example: "she/her"  
  bio              : "Short biography for the left-hand sidebar"
  location         : "Saskatoon, Canada"
  employer         : "Red Brick University"
  uri              : # URL
  email            : "none@example.org" 
theme: jekyll-theme-minimal
